apiversion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
-  patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: geostore-deployment
    spec:
      template:
        spec:
          containers:
          - name: geostore
            envFrom:
            - configMapRef:
                name: service1-env-vars
            env:
            - name: ACCOUNT_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: service1-env-vars
                  key: DBCOSMOSURL
            - name: AUTH_KEY
              valueFrom:
                configMapKeyRef:
                  name: service1-env-vars
                  key: DBCOSMOSKEY
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: service1-env-vars
                  key: DBNAME
            - name: CONTAINER_NAME
              valueFrom:
                configMapKeyRef:
                  name: service1-env-vars
                  key: CONTAINERNAME

# TODO: how to re-enable the suffix hash?
