apiVersion: apps/v1
kind: Deployment
metadata:
  name: geostore-deployment
  namespace: geostore-simple
  labels:
    app: geostore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geostore
  template:
    metadata:
      labels:
        app: geostore
    spec:
      containers:
      - name: geostore
        image: clarkezone/geostore:main
        ports:
        - containerPort: 5000
        env:
        - name: ACCOUNT_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: config-fe
              key: COSMOSURL
        - name: AUTH_KEY
          valueFrom:
            secretKeyRef:
              name: cosmoskey-secret
              key: COSMOSKEY
        - name: COSMOS_CONTAINER
          valueFrom:
            configMapKeyRef:
              name: config-fe
              key: COSMOS_CONTAINER