apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: geostore-api
commonLabels:
  app: geostore-api
resources:
- resources/deployment.yaml
- resources/service.yaml

patches:
- target:
    kind: Deployment
    name: geostore-deployment
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 1

#secretGenerator:
#- name: cosmoskey-secret
#  env: .env
#  behavior: merge
