apiVersion: apps/v1
kind: Deployment
metadata:
  name: geostore-deployment
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: geostore
        image: clarkezone/geostore:sha-2c64bff
        ports:
        - containerPort: 5000
